[package]
name    = "viewer"
version = "0.0.1"
edition = "2021"

[dependencies]
gl             = "0.10.0"
glfw           = "0.23.0"
nalgebra-glm   = "0.18"
oasis_bindings = { path = "../oasis_bindings" }
